image: Visual Studio 2017
before_build:
- nuget update -self
- nuget restore
platform:
- Any CPU
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build:
  project: MangaReader.sln 
  verbosity: normal
configuration:
- Debug
test: off
after_build:
  - nuget install OpenCover -Version 4.6.519 -ExcludeVersion
  - nuget install NUnit.Runners -Version 3.7.0 -ExcludeVersion
  - pip install codecov

  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"NUnit.ConsoleRunner/tools/nunit3-console.exe"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.API\bin\Debug\Tests.API.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -oldstyle
  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"NUnit.ConsoleRunner/tools/nunit3-console.exe"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.Entities\bin\Debug\Tests.Entities.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -oldstyle
  - codecov -f "coverage.xml"

  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp2.1 /p:PublishDir=bin\Publish\netcoreapp2.1\win-x64\ /p:SelfContained=true /p:RuntimeIdentifier=win7-x64
  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp2.1 /p:PublishDir=bin\Publish\netcoreapp2.1\linux-x64\ /p:SelfContained=true /p:RuntimeIdentifier=linux-x64
  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp2.1 /p:PublishDir=bin\Publish\netcoreapp2.1\osx-x64\ /p:SelfContained=true /p:RuntimeIdentifier=osx-x64

artifacts:
  - path: MangaReader\bin\$(configuration)
    name: WPF App
    type: zip

  - path: MangaReader.Avalonia\bin\$(configuration)
    name: Avalonia app (dotnet core required)
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp2.1\win-x64
    name: Avalonia app win-x64
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp2.1\linux-x64
    name: Avalonia app linux-x64
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp2.1\osx-x64
    name: Avalonia app osx-x64
    type: zip

  - path: '**\*.log'
    name: test logs
