image: Visual Studio 2019
before_build:
- nuget update -self
- nuget restore
platform:
- Any CPU
build:
  project: MangaReader.sln 
  verbosity: normal
configuration:
- Debug
test: off
after_build:
  - nuget install OpenCover -Version 4.7.995-rc -ExcludeVersion
  - pip install codecov

  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register -output:.\coverage.xml -target:"dotnet.exe"  -targetargs:"test" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All
  - codecov -f "coverage.xml"

  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp3.0 /p:PublishDir=bin\Publish\netcoreapp3.0\win-x64\ /p:SelfContained=true /p:RuntimeIdentifier=win7-x64
  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp3.0 /p:PublishDir=bin\Publish\netcoreapp3.0\linux-x64\ /p:SelfContained=true /p:RuntimeIdentifier=linux-x64
  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp3.0 /p:PublishDir=bin\Publish\netcoreapp3.0\osx-x64\ /p:SelfContained=true /p:RuntimeIdentifier=osx-x64

artifacts:
  - path: MangaReader\bin\$(configuration)
    name: WPF App
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp3.0\win-x64
    name: Avalonia app win-x64
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp3.0\linux-x64
    name: Avalonia app linux-x64
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp3.0\osx-x64
    name: Avalonia app osx-x64
    type: zip

  - path: '**\*.log'
    name: test logs
