os: Visual Studio 2015
before_build:
  - nuget restore
platform:
- Any CPU
build:
  project: MangaReader.sln 
  verbosity: normal
configuration:
- Release
test: off
artifacts:
  - path: '**\*.log'
    name: test logs
    type: zip
after_build:
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.API\bin\Release\Tests.API.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.Entities\bin\Release\Tests.Entities.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"
