image: Visual Studio 2017
before_build:
- nuget update -self
- nuget restore
platform:
- Any CPU
build:
  project: MangaReader.sln 
  verbosity: normal
configuration:
- Release
test: off
artifacts:
  - path: '**\*.log'
    name: test logs
    type: zip
after_build:
  - nuget install OpenCover -ExcludeVersion
  - pip install codecov

  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test .\Tests\Tests.API\Tests.API.csproj" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -oldstyle
  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test .\Tests\Tests.Convertation\Tests.Convertation.csproj" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -oldstyle
  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test .\Tests\Tests.Entities\Tests.Entities.csproj" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -oldstyle
  - codecov -f "coverage.xml"
