image: Visual Studio 2019
before_build:
- nuget update -self
- nuget restore
platform:
- Any CPU
build:
  project: MangaReader.sln 
configuration:
- Debug
test: off
after_build:
  - nuget install OpenCover -Version 4.6.519 -ExcludeVersion
  - pip install codecov

  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register -output:.\coverage.xml -target:"dotnet.exe"  -targetargs:"test" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -oldstyle
  - codecov -f "coverage.xml"

  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp3.0 /p:PublishDir=bin\Publish\netcoreapp3.0\win-x64\ /p:SelfContained=true /p:RuntimeIdentifier=win7-x64
  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp3.0 /p:PublishDir=bin\Publish\netcoreapp3.0\linux-x64\ /p:SelfContained=true /p:RuntimeIdentifier=linux-x64
  - dotnet publish MangaReader.Avalonia\MangaReader.Avalonia.csproj /p:Configuration=Debug /p:Platform=AnyCPU /p:TargetFramework=netcoreapp3.0 /p:PublishDir=bin\Publish\netcoreapp3.0\osx-x64\ /p:SelfContained=true /p:RuntimeIdentifier=osx-x64

artifacts:
  - path: MangaReader\bin\$(configuration)
    name: MangaReader_%APPVEYOR_BUILD_VERSION%.zip
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp3.0\win-x64
    name: MangaReader.Avalonia.Windows_%APPVEYOR_BUILD_VERSION%.zip
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp3.0\linux-x64
    name: MangaReader.Avalonia.Linux_%APPVEYOR_BUILD_VERSION%.zip
    type: zip

  - path: MangaReader.Avalonia\bin\Publish\netcoreapp3.0\osx-x64
    name: MangaReader.Avalonia.macOS_%APPVEYOR_BUILD_VERSION%.zip
    type: zip

  - path: '**\*.log'
    name: test logs
