image: Visual Studio 2017
before_build:
- nuget update -self
- nuget restore
platform:
- Any CPU
build:
  project: MangaReader.sln 
  verbosity: normal
configuration:
- Release
test: off
artifacts:
  - path: '**\*.log'
    name: test logs
    type: zip
after_build:
  - nuget.exe install OpenCover -ExcludeVersion
  - pip install codecov

  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"nunit3-console"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.API\bin\Release\Tests.API.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All
  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"nunit3-console"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.Entities\bin\Release\Tests.Entities.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All
  - OpenCover\tools\OpenCover.Console.exe -returntargetcode -mergeoutput -register:user -output:.\coverage.xml -target:"nunit3-console"  -targetargs:"\"C:\projects\mangareader\Tests\Tests.Convertation\bin\Release\Tests.Convertation.dll\"" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All
  - codecov -f "coverage.xml"
