os: Visual Studio 2015
before_build:
  - nuget restore
platform:
- Any CPU
build:
  project: MangaReader.sln 
  verbosity: normal
configuration:
- Release
after_build:
- packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -mergebyhash -register:user -returntargetcode -output:.\coverage.xml -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"  -targetargs:"/logger:Appveyor \"C:\projects\mangareader\Tests\Tests.API\bin\Release\Tests.API.dll\" \"C:\projects\mangareader\Tests\Tests.Convertation\bin\Release\Tests.Convertation.dll\" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"
